import type { 
  User, 
  Document, 
  Machine, 
  Collection, 
  Incident, 
  Employee, 
  Payroll 
} from './types';

// ==================== USUARIOS MOCK ====================

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin Usuario',
    email: 'admin@lifyvending.com',
    role: 'admin',
  },
  {
    id: '2',
    name: 'Gestor Usuario',
    email: 'gestor@lifyvending.com',
    role: 'gestor',
  },
  {
    id: '3',
    name: 'Operador Usuario',
    email: 'operador@lifyvending.com',
    role: 'operador',
  },
];

// ==================== DOCUMENTOS MOCK ====================

export const mockDocuments: Document[] = [
  {
    id: '1',
    docType: 'RECIBIDA',
    title: 'Factura proveedor Coca-Cola',
    counterparty: 'Coca-Cola Europacific Partners',
    amount: 2450.80,
    currency: 'EUR',
    invoiceNumber: 'FAC-2026-001234',
    invoiceDate: new Date('2026-02-15'),
    uploadedBy: 'Admin Usuario',
    uploadedAt: new Date('2026-02-16'),
    statusReview: 'REVISADA',
    reviewedAt: new Date('2026-02-17'),
    reviewedBy: 'Gestor Usuario',
    statusAccounting: 'CONTABILIZADA',
    accountedAt: new Date('2026-02-18'),
    accountedBy: 'Gestor Usuario',
    tags: ['proveedores', 'bebidas'],
    notes: 'Pedido mensual de bebidas',
    fileUrl: '/mock/factura-cocacola.pdf',
    accountingPeriod: '2026-02',
    visibility: 'AMBOS',
    historyEvents: [
      {
        id: '1',
        date: new Date('2026-02-16'),
        action: 'Subida',
        userId: '1',
        userName: 'Admin Usuario',
      },
      {
        id: '2',
        date: new Date('2026-02-17'),
        action: 'Marcada como revisada',
        userId: '2',
        userName: 'Gestor Usuario',
      },
    ],
  },
  {
    id: '2',
    docType: 'RECIBIDA',
    title: 'Factura electricidad',
    counterparty: 'Iberdrola',
    amount: 350.25,
    currency: 'EUR',
    invoiceNumber: 'ELEC-2026-02',
    invoiceDate: new Date('2026-02-01'),
    uploadedBy: 'Admin Usuario',
    uploadedAt: new Date('2026-02-05'),
    statusReview: 'PENDIENTE',
    statusAccounting: 'PENDIENTE',
    tags: ['servicios', 'electricidad'],
    fileUrl: '/mock/factura-iberdrola.pdf',
    accountingPeriod: '2026-02',
    visibility: 'AMBOS',
    historyEvents: [],
  },
  {
    id: '3',
    docType: 'ABONADA',
    title: 'Factura cliente Centro Comercial',
    counterparty: 'Centro Comercial ABC',
    amount: 1200.00,
    currency: 'EUR',
    invoiceNumber: 'FAC-EMIT-2026-015',
    invoiceDate: new Date('2026-02-20'),
    uploadedBy: 'Admin Usuario',
    uploadedAt: new Date('2026-02-20'),
    statusReview: 'REVISADA',
    reviewedAt: new Date('2026-02-21'),
    reviewedBy: 'Gestor Usuario',
    statusAccounting: 'PENDIENTE',
    tags: ['clientes', 'comisiones'],
    notes: 'Comisión mensual 15%',
    fileUrl: '/mock/factura-emitida.pdf',
    accountingPeriod: '2026-02',
    visibility: 'EMPRESA',
    historyEvents: [],
  },
];

// ==================== MÁQUINAS MOCK ====================

export const mockMachines: Machine[] = [
  {
    id: '1',
    machineNumber: 'VM-001',
    type: 'mixta',
    brand: 'Necta',
    model: 'Jazz',
    serialNumber: 'NEC-2024-001234',
    hasCardReader: true,
    hasTelemetry: true,
    hasContract: true,
    contractFileUrl: '/mock/contrato-vm-001.pdf',
    locationName: 'Hospital Universitario',
    locationAddress: 'Av. Principal 123, Madrid',
    contactPerson: 'María García',
    contactPhone: '+34 600 123 456',
    installationDate: new Date('2025-06-15'),
    status: 'ACTIVA',
    commissionPercentage: 15,
    notes: 'Máquina principal de la entrada',
    documents: [],
    historyEvents: [],
  },
  {
    id: '2',
    machineNumber: 'VM-002',
    type: 'snack',
    brand: 'Azkoyen',
    model: 'Palma',
    serialNumber: 'AZK-2024-005678',
    hasCardReader: true,
    hasTelemetry: false,
    hasContract: true,
    contractFileUrl: '/mock/contrato-vm-002.pdf',
    locationName: 'Oficinas Tech Corp',
    locationAddress: 'C/ Innovación 45, Barcelona',
    contactPerson: 'Juan Pérez',
    contactPhone: '+34 600 789 012',
    installationDate: new Date('2025-09-20'),
    status: 'ACTIVA',
    commissionPercentage: 20,
    documents: [],
    historyEvents: [],
  },
  {
    id: '3',
    machineNumber: 'VM-003',
    type: 'cafe',
    brand: 'Saeco',
    model: 'Aulika',
    serialNumber: 'SAE-2025-001122',
    hasCardReader: false,
    hasTelemetry: true,
    hasContract: false,
    locationName: 'Universidad Politécnica',
    locationAddress: 'Campus Sur, Valencia',
    installationDate: new Date('2026-01-10'),
    status: 'AVERIADA',
    commissionPercentage: 10,
    notes: 'Avería en el sistema de agua',
    documents: [],
    historyEvents: [],
  },
];

// ==================== RECAUDACIONES MOCK ====================

export const mockCollections: Collection[] = [
  {
    id: '1',
    machineId: '1',
    date: new Date('2026-02-15'),
    cashAmount: 145.50,
    cardAmount: 234.80,
    totalAmount: 380.30,
    clientCommission: 57.05,
    commissionPaid: true,
    commissionPaidDate: new Date('2026-02-20'),
    commissionNotes: 'Pagado el 20/02/2026',
    collectedBy: 'Operador Usuario',
    notes: 'Recaudación normal',
  },
  {
    id: '2',
    machineId: '2',
    date: new Date('2026-02-20'),
    cashAmount: 89.20,
    cardAmount: 156.40,
    totalAmount: 245.60,
    clientCommission: 49.12,
    commissionPaid: false,
    collectedBy: 'Operador Usuario',
  },
  {
    id: '3',
    machineId: '1',
    date: new Date('2026-02-22'),
    cashAmount: 178.60,
    cardAmount: 298.20,
    totalAmount: 476.80,
    clientCommission: 71.52,
    commissionPaid: false,
    collectedBy: 'Operador Usuario',
  },
];

// ==================== INCIDENCIAS MOCK ====================

export const mockIncidents: Incident[] = [
  {
    id: '1',
    machineId: '3',
    date: new Date('2026-02-25'),
    type: 'electrica',
    description: 'Sistema de agua no funciona, posible problema eléctrico',
    status: 'ABIERTA',
    assignedTo: 'Técnico Juan',
    images: [],
    notes: 'Revisión urgente necesaria',
  },
  {
    id: '2',
    machineId: '1',
    date: new Date('2026-02-18'),
    type: 'atasco',
    description: 'Producto atascado en espiral 43',
    status: 'CERRADA',
    assignedTo: 'Operador Usuario',
    resolvedAt: new Date('2026-02-18'),
    images: [],
    notes: 'Resuelto durante recaudación',
  },
  {
    id: '3',
    machineId: '2',
    date: new Date('2026-02-20'),
    type: 'lector',
    description: 'Lector de tarjetas no lee algunas tarjetas',
    status: 'EN_PROCESO',
    assignedTo: 'Técnico María',
    images: [],
  },
];

// ==================== EMPLEADOS MOCK ====================

export const mockEmployees: Employee[] = [
  {
    id: '1',
    name: 'Soledad',
    dni: '12345678A',
    position: 'Gerente',
    startDate: new Date('2020-01-15'),
    active: true,
  },
  {
    id: '2',
    name: 'Fernando',
    dni: '87654321B',
    position: 'Operador',
    startDate: new Date('2021-03-20'),
    active: true,
  },
];

// ==================== NÓMINAS MOCK ====================

export const mockPayrolls: Payroll[] = [
  {
    id: '1',
    employeeId: '1',
    month: 2,
    year: 2026,
    grossAmount: 2500.00,
    netAmount: 2000.00,
    companyCost: 3000.00,
    uploadedAt: new Date('2026-02-28'),
    status: 'REVISADA',
    fileUrl: '/mock/nomina-soledad-02-2026.pdf',
    notes: 'Nómina regular',
  },
  {
    id: '2',
    employeeId: '2',
    month: 2,
    year: 2026,
    grossAmount: 1800.00,
    netAmount: 1500.00,
    companyCost: 2200.00,
    uploadedAt: new Date('2026-02-28'),
    status: 'PENDIENTE',
    fileUrl: '/mock/nomina-fernando-02-2026.pdf',
  },
  {
    id: '3',
    employeeId: '1',
    month: 1,
    year: 2026,
    grossAmount: 2500.00,
    netAmount: 2000.00,
    companyCost: 3000.00,
    uploadedAt: new Date('2026-01-31'),
    status: 'REVISADA',
    fileUrl: '/mock/nomina-soledad-01-2026.pdf',
  },
];
